- lua/Comment/comment.lua
- lua/Comment/utils.lua
This happens if the first line has greater indentation than the next line. In this case, we need to calculate the indentation of the minimum length but don't consider any empty line. So that comments would be aligned with the shortest line.
> fix: messed up comment indentation

- dump.lua
- lua/Comment/comment.lua
- lua/Comment/init.lua
- lua/Comment/utils.lua
Now you can ignore lines by giving a Lua regex to `ignore` in setup. Show below
```lua
require('Comment').setup({
-- Following ignores any empty lines
ignore = '^$'
})
```
> feat: `ignore` lines

- README.md
Hey! `nvim-ts-context-commentstring` got a new configuration parameter for `calculate_commentstring` which allows configuring the location where the `commentstring` is calculated from. By default it is the start of the cursor's line, but we can make it smarter based on if the user is visually selecting something or is performing a motion.
This helps in this case in a Vue file for example:
```vue
v---------v injected TypeScript
<button @click="handleClick">Hello</button>
^ cursor
```
Performing `gciw` would now correctly result in the following:
```vue
<button @click="/* handleClick */">Hello</button>
```
Instead of:
```vue
<button @click="">Hello</button>
```
Related PR: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/pull/28
Also fixes this case: …
> Update nvim-ts-context-commentstring example

- lua/Comment/opfunc.lua
- lua/Comment/utils.lua
Resolves #70 
Now you can do this
```lua
require('Comment').setup({
pre_hook = function(ctx)
local lines = require('Comment.utils').get_lines(ctx.range)
local srow = ctx.range.erow
vim.api.nvim_buf_set_lines(0, srow, srow, false, lines)
end,
post_hook = function(ctx)
local U = require('Comment.utils')
local srow = ctx.range.erow
local erow = srow + 1
local line = U.get_lines({ srow = srow, erow = erow })
local _, col = U.grab_indent(line[1])
vim.api.nvim_win_set_cursor(0, { erow, col })
end,
})
````
https://user-images.githubusercontent.com/24727447/142718954-5507daa1-a0c3-4f02-94c5-c407f43a74e4.mp4
> chore: refactor `utils.get_lines`

- README.md
- lua/Comment/comment.lua
- lua/Comment/extra.lua
- lua/Comment/opfunc.lua
Now range can be accessed via `ctx.range`
> BREAKING: remove redundant range(s) args from `post_hook`

- API.md
- README.md
- doc/API.md
- dump.lua
- lua/Comment/api.lua
- lua/Comment/comment.lua
- lua/Comment/init.lua
- lua/Comment/opfunc.lua
- lua/Comment/utils.lua
Previously, all those functions were kinda available via the global scope but there was no guarantee that those will stay that way.
Now the objective is to properly expose them and treat them as the API of the plugin and remove all the global functions.
> feat: lua api for `gc`, `gcc`, `gb`, `gbc` 🎉 

- README.md
- lua/Comment/api.lua
`gcb` is `gc` followed by a motion `b`, while `gbc` is block-commenting
the whole line.
> docs: gcb -> gbc

- README.md
Fixed `make to sure` -> `make sure` in readme
> Fixed typo in readme text

- lua/Comment/utils.lua
When mode is 'n' then the keys are _appended_ to the typeahead buffer,
which can add them _after_ other keys in a mapping. Using 'ni' instead
inserts them, so that keys later in the binding remain later in the
buffer.
This allows mappings such as:
`"gcATODO<ESC>"`
to work as expected.
Fixes #88
> Use mode 'ni' for nvim_feedkeys

- README.md
- doc/API.md
- lua/Comment/api.lua
- lua/Comment/opfunc.lua
Now you can press any number followed by `gbc`. For example:
`4gbc` -> toggle blockwise comment on 4 lines (including current line)
---
Closes #95
> feat: add `count` support for `gbc`

- lua/Comment/ft.lua
This fixes comments in svelte html context. Scripts seem to work already as well as line comments in css. However, block comments in css (inside a svelte file) do not use the correct commentstring.
> feat: add `svelte` support

- lua/Comment/ft.lua
Noticed some issues with trying to comment out a vanilla Ruby file:
> feat: add ruby support

- lua/Comment/api.lua
Using `nvim_buf_set_lines` destroys the marks within the (un)comment region.
To prevent that I am now wrapping every API function with `lockmarks` which
will preserve the marks inside the region.
Fixes #24 #76
> fix: marks disappears after (un)comment

- lua/Comment/ft.lua
includes fennel, lisp and scheme filetypes
> feat: add `lisp` support

- .gitignore
- README.md
- lua/Comment/api.lua
- lua/Comment/config.lua
> feat: dot-repeat support for `[count]gcc` and `[count]gbc` 🎉

- lua/Comment/extra.lua
`insert_eol()` used to always add one space in front of the comment. In this PR it checks if the line is empty, and if it is, no space is added in front of the comment.
Here's an example:
```lua
1. local value = 1
2.
3. print(value)
```
Before, pressing `gcA` with cursor on line 2 and then typing the word `comment` would result in the following:
```lua
1. local value = 1
2.  -- comment
3. print(value)
```
Now it will look like this:
```lua
1. local value = 1
2. -- comment
3. print(value)
```
An even neater solution would be to use `vim.fn.indent('.')` to calculate the indent level, which would always give the comment a correct indent level in case the line is in an indented environment, for instance inside a function definition or something like that. However I couldn't figure out how to …
> Don't add space in front of comment on empty lines with `insert_eol()`

- lua/Comment/utils.lua
When using an API function on a single line with embedded code, the commentstring detected using treesitter is not correct when using the cursor position. To fix this, I am changing the column position being parsed when vmode is set to nil.
> change: use starting column when using `*_current_*` apis

- lua/Comment/ft.lua
This PR fixes commenting in nested (injected) code blocks. Like in markdown you can have multiple code blocks and those code blocks can also have injected languages for example `markdown -> vue -> css/js`
```vue
<style>
body {
}
</style>
<script>
while (true) {
}
</script>
```
```vue
<style>
body {
/* color: red; */
}
</style>
<script>
while (true) {
// console.log("neovim is awesome!");
}
</script>
```
---
Closes #137
> feat: support nested (injected) code blocks

- README.md
- doc/API.md
- lua/Comment/api.lua
- lua/Comment/config.lua
- lua/Comment/extra.lua
- lua/Comment/ft.lua
- lua/Comment/init.lua
- lua/Comment/opfunc.lua
- lua/Comment/utils.lua
Pending
~Help can't be generated for the following:~
~- [ ] `ft.lua`~
~- [ ] `config.lua`~
I'll take care of help generation later
> chore: tweak emmylua docs

- README.md
- lua/Comment/api.lua
- lua/Comment/config.lua
- lua/Comment/extra.lua
- lua/Comment/ft.lua
- lua/Comment/opfunc.lua
- lua/Comment/utils.lua
- `utils.commenter()`
- `utils.uncommenter()`
- `utils.{unwrap_cstr,parse_cstr}()` now returns `string, string` instead of `string|bool, string|bool`
- Merged `Op.blockwise_x()` with `Op.blockwise()`
- Removed `utils.get_padding()`, `utils.move_n_insert()` and `utils.grab_indent()`
- Removed `utils.comment_str()` (Use `utils.commenter()`)
- Removed `utils.uncomment_str()` (Use `utils.uncommenter()`)
- Changed `utils.is_commented()` function signature.
---
This will break your setup if you are depending on the internal functions. So feel free ask anything regarding the above changes.
Resolve #177
> chore!: refactoring

- doc/plugs.md
- lua/Comment/api.lua
https://github.com/neovim/neovim/pull/19598 changed `vim.keymap.set` to replace keycodes by default for all mappings if `expr == true` instead of only luaref expr mappings.
The toggle expr mappings are not luarefs but shouldn't have the keycodes replaced since they use `<Plug>`.
> Add `replace_keycodes=false` to expr mappings

- after/plugin/Comment.lua
- lua/Comment/api.lua
Let me know if you're happy with the descriptions I added, here's a screenshot of the final result:
> feat: Add keymap descriptions

- README.md
This PR will solve this issue: https://github.com/numToStr/Comment.nvim/issues/195.
> docs(readme): `toggler` doesn't defines mappings in visual mode

- lua/Comment/api.lua
- plugin/Comment.lua
Now `g@` is returned from the RHS callback of every operator-mode keybindings i.e., `gc[motion]`, `gcc` etc.. Instead of using a command we are now using a callback as the RHS and returning `g@` from that callback to used as an expression, which will be executed by neovim using `{ expr = true }` option. `<Plug>` mappings are also covered in this fix.
- Before
```lua
vim.keymap.set('n', 'gc', '<CMD>lua require("Comment.api").call("toggle.linewise")<CR>g@')
```
- After
```lua
vim.keymap.set('n', 'gc', require("Comment.api").call("toggle.linewise", "g@"), { expr = true })
```
> This PR also changes the `.call()` method signature, now it returns a function which is used to create keymap RHS
---
Fixes #143
> fix!: `i_<C-o>gcc` inserts `g@$`

- lua/Comment/ft.lua
In case you never heard of it: [Nushell](https://www.nushell.sh/book/scripts.html)
> feat: add `nu` support

- lua/Comment/ft.lua
https://github.com/nvim-treesitter/nvim-treesitter/pull/3303#issuecomment-1215900112
Detect gitignore need following
```
augroup filetypedetect
au! BufRead,BufNewFile .gitignore set filetype=gitignore
augroup end
```
> feat: add `gitignore` support

- lua/Comment/api.lua
> fix: remove `lockmarks` from `gc{o,O}`

- lua/Comment/opfunc.lua
- lua/Comment/utils.lua
> fix: empty line indentation when using tabs

- README.md
- lua/Comment/api.lua
- lua/Comment/config.lua
Ref: https://github.com/numToStr/Comment.nvim/discussions/247
> chore!: deprecate `extended` keybindings

- lua/Comment/api.lua
- lua/Comment/config.lua
Previously, when you press `3gcc` 3 lines will be (un)commented then pressing `.` also (un)comments 3 lines. This is fine. But if you press `4.` (prefixing the `.` with a `count`) it (un)comments 3 lines instead of 4 which is wrong. As `.` repeat should respect the updated value of the `v:count`, in this case, `4` should be used instead of `3`.
With this PR, `.` will respect the updated value of `v:count` by removing an old workaround. This PR also replaces `vim.v.count` with `vim.api.nvim_get_vvar('count')`.
> fix: respect updated `v:count` when using `.` repeat

- lua/Comment/api.lua
- lua/Comment/ft.lua
- lua/Comment/opfunc.lua
- lua/Comment/utils.lua
This adds error handling to the plugin, implemented with the help of `assert` and `xpcall`. Adding explicit error handling for the following cases:
- Invalid commenstring / Commenting is not supported like `json`
- When filetype doesn't support block comments like `yaml`
- Graceful handling of certain cases like uncommenting when there is nothing to uncomment.
---
fixes #221 
supersedes #277
> chore!: error handling

- lua/Comment/ft.lua
This adds the default commenting style for [vifm config files](https://github.com/vifm/vifm).
> adding vifm ft

- lua/Comment/ft.lua
https://www.autohotkey.com/docs/v1/Language.htm#comments
https://www.autohotkey.com/docs/v2/Language.htm#comments
This includes block comments, but autohotkey restricts the end tag to appearing at the start of a line, or in v2 at the end of a line. With those restrictions, it may be better to only define the line comment.
> feat: add autohotkey support

- lua/Comment/ft.lua
This requires the `nvim-treesiter` plugin, as the quarto filetype does not yet have its own treesitter grammar, and this now merged PR in nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/pull/4212/files
It also makes Comment.nvim work for the other languages in the same list:
https://github.com/nvim-treesitter/nvim-treesitter/blob/cda8b291ef6fc4e04036e2ea6cf0de8aa84c2656/lua/nvim-treesitter/parsers.lua#L4-L23
> feat: add quarto filetype and enable languages using other languages' parsers

- lua/Comment/ft.lua
This PR removes the workaround needed for converting filetype to parser name. Neovim now provides proper API to deal with this ambiguity, which is also respected by nvim-treesitter and for most cases this conversion is automatic.
This was introduced in 
- #301
Supersedes #326
Fixes #325
> chore!: remove internal filetype to parser name aliases

- lua/Comment/ft.lua
Submitting this PR to add support for Protobuf (*.proto) files. It supports both line and block commenting.
> feat(ft): add `proto` (Protobuf) support

- lua/Comment/ft.lua
Doc: https://www.kernel.org/doc/Documentation/devicetree/booting-without-of.txt
`The format of the .dts "source" file is "C" like, supports C and C++ style comments.`
> feat(ft): add `dts` support

- lua/Comment/ft.lua
This PR adds support for the [Nextflow](https://www.nextflow.io/) (`nextflow`) filetype,. Nextflow is a Groovy-based workflow management system used heavily in _e.g._ bioinformatics.
> feat(ft): add `nextflow` support

- lua/Comment/ft.lua
Idris 2 uses its own ft for some reason (probably due to it being very non-backwards compatible since it uses QTT and an entirely different compiler).
> feat(ft): add `idris2` support

- lua/Comment/ft.lua
Submitting this PR to add support for [Robotframework](https://robotframework.org/) (*.robot) files. Robotframework **doesn't** have block comments.
> feat(ft): add `robot` (Robotframework) support

- lua/Comment/ft.lua
Came across the RON format while configuring `gitui` and wanted to use some comments :)
See specification here:
* basic: https://github.com/ron-rs/ron/wiki/Specification#comments
* actual grammar: https://github.com/ron-rs/ron/blob/master/docs/grammar.md#whitespace-and-comments
(small thing, the basic doc don't include the block comment (`/* */`) for some reason, the actual spec does though.
> feat(ft): add `ron` support

- lua/Comment/ft.lua
SBT files are essentially Scala files and exist in most Scala projects. It supports the same comments as scala.
> feat(ft): add `sbt` support

- lua/Comment/ft.lua
ft=lean seems to be specifically for lean4. See https://github.com/Julian/lean.nvim/blob/main/ftdetect/lean.lua.
> feat(ft): add `lean3` support

- README.md
An alternative to https://github.com/numToStr/Comment.nvim/pull/367 , without listing out all the keys.
> docs(plugin): add `lazy.nvim` install instruction

- README.md
`lazy=false` is a default value for lazy.nvim. Explicitly setting it is redundant and leaves users confused. As a new user, I assumed lazy-loading Comment.nvim would break the plugin, but that's not the case.
> Remove lazy=false

- lua/Comment/ft.lua
.hcl files are the same as .tf files, fixes #382.
> Add support for .hcl files

- lua/Comment/ft.lua
[GNU assembler](https://en.wikipedia.org/wiki/GNU_Assembler) use `#` to comment string for x86-64 and RISC-V
> feat(ft): add asm support

- lua/Comment/ft.lua
Add support for filetype `gdshader`, which is the shader programming language of [Godot game engine](https://github.com/godotengine/godot).
Comment rules are explained [here](https://docs.godotengine.org/en/stable/tutorials/shaders/shaders_style_guide.html#comment-spacing).
> feat(ft): add gdshader support
