lua/Comment/utils.lua
=> fix(css): invalid line comment on empty lines

README.md, lua/Comment/api.lua
=> feat: allow `extra` mapping to be configured

README.md
@tjdevries made a nice video about https://github.com/numToStr/Comment.nvim
=> Add link to video by TJ DeVries

lua/Comment/ft.lua
This adds teal-lang filetype support.
=> feat: add teal support

lua/Comment/ft.lua
=> support gleam

lua/Comment/ft.lua
=> Add kotlin support

README.md
=> Readme Small Fix.

lua/Comment/ft.lua
Add CUDA to the list of supported C-like languages.
=> Add CUDA to the list of supported C-like languages.

lua/Comment/ft.lua
Solidity docs: https://docs.soliditylang.org/en/latest/layout-of-source-files.html#comments
=> feat: add `Solidity` support

lua/Comment/ft.lua
Elvish docs: https://elv.sh/ref/
=> feat: add `elvish` support

lua/Comment/ft.lua
Jsonnet docs: https://jsonnet.org/
=> feat: Add `jsonnet` support

README.md, lua/Comment/ft.lua
=> feat: support compound (dot-separated) filetypes

lua/Comment/ft.lua
https://learnxinyminutes.com/docs/nim/
=> Add nim comments

lua/Comment/ft.lua
[Documentation](https://lilypond.org/doc/v2.22/Documentation/learning/working-on-input-files.html)
=> Add `lilypond` support

lua/Comment/ft.lua
luau is a kind of lua but with typechecking
=> feat: add `luau` support

lua/Comment/ft.lua
Does what it says on the tin. Thanks! :)
=> Add Supercollider and Faust support

lua/Comment/ft.lua
=> add remind support (#315)

lua/Comment/ft.lua
Ref: https://elkowar.github.io/eww/configuration.html
=> feat: add `yuck` support

lua/Comment/ft.lua
Support for [Odin](https://odin-lang.org/)
=> feat(ft): add `odin` support

lua/Comment/ft.lua
- Add default commentstring for verilog files
=> feat(ft): add `verilog` commentstring

lua/Comment/ft.lua
https://opensource.apple.com/source/lldb/lldb-76/llvm/docs/TableGenFundamentals.html#comments
https://llvm.org/docs/TableGen/ProgRef.html#lexical-analysis
=> add tablegen comment type

lua/Comment/ft.lua
Support for the mermaid [Mermaid](https://mermaid.js.org/) diagramming and charting tool
=> feat(ft): add `mermaid` support

lua/Comment/ft.lua
Edited ft.lua and added support for FunC language.
=> feat(ft): add `func` support

lua/Comment/ft.lua
Doc: https://haxe.org/manual/introduction-hello-world.html
No comment specific documentation exists (HaxeFoundation/HaxeManual/issues/478)
=> feat(ft): add `haxe` support

lua/Comment/ft.lua
Would appreciate if VHDL support could be added.
=> feat(ft): add `vhdl` support

lua/Comment/ft.lua
See https://coq.github.io/doc/v8.9/refman/language/gallina-specification-language.html
=> feat(ft): add `coq` support

lua/Comment/ft.lua
=> feat: add puppet configuration

lua/Comment/ft.lua
Comment string for jq language: <https://jqlang.github.io/jq/>
=> feat(ft): add `jq` support

lua/Comment/ft.lua
[Vala Comments](https://wiki.gnome.org/Projects/Vala/Tutorial#Comments)
=> feat(ft): add `vala` support

lua/Comment/ft.lua
Add support for [KDL](https://kdl.dev/) files.
=> feat(ft): Add KDL support

lua/Comment/ft.lua
add support for mojo, same as the python one :)
=> add mojo support

lua/Comment/ft.lua
https://github.com/numToStr/Comment.nvim/assets/5561166/41087cb4-8776-4072-ac3d-b56432915e65
=> Add blocks for ruby

doc/Comment.txt
=> fix mistake in documentation
